In [138]:
import pandas as pd
import os
pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

import pandas as pd
import os

pd.options.mode.chained_assignment = None
import numpy as np
# Define the directory path where the files are located

# Initialize an empty DataFrame to store the merged data
df =  pd.read_excel("merged_data.xlsx" ,header=None  )

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,District,"Laboratory confirmed, since the beginning of the pandemic TOTAL","Laboratory confirmed, since the beginning of the pandemic Difference from","Laboratory confirmed, since the beginning of the pandemic Hospitalized","Laboratory confirmed, since the beginning of the pandemic Deceased","Laboratory confirmed, since the beginning of the pandemic RecoveredA","Laboratory confirmed, since the beginning of the pandemic Current CasesB","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,Rheinland-Pfalz","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE"
1,Ahrweiler,4577,4,199,52,4423,102,50,50,132.2,49,7.1
2,Altenkirchen,4956,0,411,101,4833,22,8.5,8.5,8.4,12.1,2.6
3,Alzey-Worms,5130,1,304,123,4970,37,9.3,9.3,24,4.4,8.2
4,Bad Dürkheim,4499,1,305,150,4303,46,14.3,14.3,21.6,19.5,2.3

In [139]:
def convert_row_to_column_header(df):
    new_header = df.iloc[0]  # Get the values from row 0
    df = df[1:]  # Exclude row 0 from the DataFrame
    df.columns = new_header  # Set the new column headers
    
    return df

df = convert_row_to_column_header(df)

In [148]:
def calculate_null_percentage(df):
    # Calculate the total number of rows in the DataFrame
    total_rows = df.shape[0]
    
    # Calculate the percentage of null values for each column
    null_percentage = ((  df.isnull().sum()  ) / total_rows) * 100
    
    # Print the columns with their corresponding null percentages
    print("Columns with null percentage:")
    print(null_percentage)



calculate_null_percentage(df)

Columns with null percentage:
0
District                                                                            0.059801
Laboratory confirmed, since the beginning of the pandemic TOTAL                     0.107643
Laboratory confirmed, since the beginning of the pandemic Difference from           0.095682
Laboratory confirmed, since the beginning of the pandemic Hospitalized              0.065782
Laboratory confirmed, since the beginning of the pandemic Deceased                  0.059801
Laboratory confirmed, since the beginning of the pandemic RecoveredA                0.131563
Laboratory confirmed, since the beginning of the pandemic Current CasesB            0.059801
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,Rheinland-Pfalz    63.389547
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD              0.047841
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre           0.053821
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE        0.053821
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE        0.053821
dtype: float64

In [161]:
del df["Reported, the last 7 days,Incidence per 100, Incidence per 100 ,Rheinland-Pfalz"]

In [268]:
df = df.replace("#", np.nan)
df = df.replace(r'^\d+\s#$', np.nan, regex=True)
df2 = df.replace("--*", np.nan)
# df = df.replace("171676 #", np.nan)

        # Define the values to be dropped
drop_values = ['Vortag','Hospitalisiert','Hospitali-siert','Rheinland-Pfalz','Verstorben','Verstor-ben','GenesenA','aktuelle FälleB','+USAFD','<20 Jahre']

# Drop rows that contain the specified values in any cell
df2 = df2[~df2.isin(drop_values)].dropna(how='all')
df2.reset_index(drop=True, inplace=True)

df2 = df2.replace(np.nan, 0)

# for col in df.columns:
#     if(col != "District"):
# #         df2[col] = df2[col].fillna(df2.groupby('District')[col].transform('median'))
#         try:
#             df2[col].fillna(-10000000, inplace=True)
#             df[col] = df[col].replace(np.nan,  )
#         except Exception as e:
#             print(e)
#             continue 


# df2.fillna(df2.mean())

In [262]:
# from sklearn.impute import SimpleImputer

# def impute_with_median_except_object_columns(df2):
#     df4 = df2.copy(deep=True)
#     # Identify columns with dtype "object"
#     object_columns = df4.select_dtypes(include=['object']).columns.tolist()
    
#     # Exclude object columns from the rest of the DataFrame
#     df_subset = df4.drop(columns=object_columns)
    
#     # Impute missing values with median for the subset DataFrame
#     imputer = SimpleImputer(strategy='median', missing_values=np.nan)
#     df_imputed = pd.DataFrame(imputer.fit_transform(df_subset), columns=df_subset.columns)
    
#     # Combine the imputed subset DataFrame with the object columns
#     df_imputed = pd.concat([df_imputed, df4[object_columns]], axis=1)
    
#     return df_imputed


# df_imputed = impute_with_median_except_object_columns(df2)
# # print(df_imputed)

In [263]:
df2.dtypes

0
District                                                                         object
Laboratory confirmed, since the beginning of the pandemic TOTAL                 float64
Laboratory confirmed, since the beginning of the pandemic Difference from         int64
Laboratory confirmed, since the beginning of the pandemic Hospitalized            int64
Laboratory confirmed, since the beginning of the pandemic Deceased                int64
Laboratory confirmed, since the beginning of the pandemic RecoveredA              int64
Laboratory confirmed, since the beginning of the pandemic Current CasesB          int64
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD          float64
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre       float64
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE     object
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE     object
dtype: object

In [260]:
df_imputed.isnull().values.any()

True

In [266]:
calculate_null_percentage(df2)

Columns with null percentage:
0
District                                                                        0.0
Laboratory confirmed, since the beginning of the pandemic TOTAL                 0.0
Laboratory confirmed, since the beginning of the pandemic Difference from       0.0
Laboratory confirmed, since the beginning of the pandemic Hospitalized          0.0
Laboratory confirmed, since the beginning of the pandemic Deceased              0.0
Laboratory confirmed, since the beginning of the pandemic RecoveredA            0.0
Laboratory confirmed, since the beginning of the pandemic Current CasesB        0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD          0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre       0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE    0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE    0.0
dtype: float64

In [264]:
df2[df2['District'].isna()]

Empty DataFrame
Columns: [District, Laboratory confirmed, since the beginning of the pandemic TOTAL, Laboratory confirmed, since the beginning of the pandemic Difference from, Laboratory confirmed, since the beginning of the pandemic Hospitalized, Laboratory confirmed, since the beginning of the pandemic Deceased, Laboratory confirmed, since the beginning of the pandemic RecoveredA, Laboratory confirmed, since the beginning of the pandemic Current CasesB, Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD, Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre, Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE, Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE]
Index: []

In [267]:
df.to_excel('merged_data2.xlsx' )