In [140]:
import pandas as pd
import os
pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

import pandas as pd
import os

pd.options.mode.chained_assignment = None
import numpy as np
# Define the directory path where the files are located

# Initialize an empty DataFrame to store the merged data
df =  pd.read_excel("merged_data4.xlsx" ,header=None  )

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,District,"Laboratory confirmed, since the beginning of the pandemic TOTAL","Laboratory confirmed, since the beginning of the pandemic Difference from","Laboratory confirmed, since the beginning of the pandemic Hospitalized","Laboratory confirmed, since the beginning of the pandemic Deceased","Laboratory confirmed, since the beginning of the pandemic RecoveredA","Laboratory confirmed, since the beginning of the pandemic Current CasesB","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,Rheinland-Pfalz","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,>=60 Jahre",Date
1,Ahrweiler,4577,4,199,52,4423,102,50,50,132.2,49,7.1,2021-08-01
2,Altenkirchen,4956,0,411,101,4833,22,8.5,8.5,8.4,12.1,2.6,2021-08-01
3,Alzey-Worms,5130,1,304,123,4970,37,9.3,9.3,24,4.4,8.2,2021-08-01
4,Bad Dürkheim,4499,1,305,150,4303,46,14.3,14.3,21.6,19.5,2.3,2021-08-01

In [141]:
def convert_row_to_column_header(df):
    new_header = df.iloc[0]  # Get the values from row 0
    df = df[1:]  # Exclude row 0 from the DataFrame
    df.columns = new_header  # Set the new column headers
    
    return df

df = convert_row_to_column_header(df)

In [142]:
def calculate_null_percentage(df):
    # Calculate the total number of rows in the DataFrame
    total_rows = df.shape[0]
    
    # Calculate the percentage of null values for each column
    null_percentage = ((  df.isnull().sum()  ) / total_rows) * 100
    
    # Print the columns with their corresponding null percentages
    print("Columns with null percentage:")
    print(null_percentage)




del df["Reported, the last 7 days,Incidence per 100, Incidence per 100 ,Rheinland-Pfalz"]
# del df["Date"]
calculate_null_percentage(df)

Columns with null percentage:
0
District                                                                        0.476417
Laboratory confirmed, since the beginning of the pandemic TOTAL                 0.524059
Laboratory confirmed, since the beginning of the pandemic Difference from       0.512149
Laboratory confirmed, since the beginning of the pandemic Hospitalized          0.482373
Laboratory confirmed, since the beginning of the pandemic Deceased              0.476417
Laboratory confirmed, since the beginning of the pandemic RecoveredA            0.476417
Laboratory confirmed, since the beginning of the pandemic Current CasesB        0.476417
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD          0.464507
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre       0.464507
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE    0.464507
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,>=60 Jahre      0.464507
Date                                                                            0.000000
dtype: float64

In [143]:
df = df.replace("#", np.nan)
df = df.replace(r'^\d+\s#$', np.nan, regex=True)
df2 = df.replace("--*", np.nan)
# df = df.replace("171676 #", np.nan)

        # Define the values to be dropped
drop_values = ['Vortag','Hospitalisiert','Hospitali-siert','Rheinland-Pfalz','Verstorben','Verstor-ben',
               'GenesenA','aktuelle FälleB','+USAFD','<20 Jahre','20-59 JahreE','≥ 60 Jahre']

# Drop rows that contain the specified values in any cell
df2 = df2[~df2.isin(drop_values)].dropna(how='all')
df2.reset_index(drop=True, inplace=True)

In [144]:
# df2 = df2[~df2.isin(drop_values)]
# df2 = df2.dropna()

In [145]:
df2.dtypes

0
District                                                                         object
Laboratory confirmed, since the beginning of the pandemic TOTAL                 float64
Laboratory confirmed, since the beginning of the pandemic Difference from        object
Laboratory confirmed, since the beginning of the pandemic Hospitalized           object
Laboratory confirmed, since the beginning of the pandemic Deceased               object
Laboratory confirmed, since the beginning of the pandemic RecoveredA             object
Laboratory confirmed, since the beginning of the pandemic Current CasesB         object
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD           object
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre        object
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE     object
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,>=60 Jahre       object
Date                                                                             object
dtype: object

In [146]:
# df2 = df2.replace(np.nan, 0)

#Fill all numeric columns
for col in df2.columns:
    if(col != "District"):
        try:
#             df = df[~df['your column'].isin(['list of strings'])]
            col_median = df2[col].median()
            df2[col] = df2[col].replace(np.nan, col_median )
        except Exception as e:
            print(e)
            continue

could not convert string to float: '2021-08-01'

In [147]:
df2.head()

,District,"Laboratory confirmed, since the beginning of the pandemic TOTAL","Laboratory confirmed, since the beginning of the pandemic Difference from","Laboratory confirmed, since the beginning of the pandemic Hospitalized","Laboratory confirmed, since the beginning of the pandemic Deceased","Laboratory confirmed, since the beginning of the pandemic RecoveredA","Laboratory confirmed, since the beginning of the pandemic Current CasesB","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,>=60 Jahre",Date
0,Ahrweiler,4577.0,4.0,199.0,52.0,4423.0,102.0,50.0,132.2,49.0,7.1,2021-08-01
1,Altenkirchen,4956.0,0.0,411.0,101.0,4833.0,22.0,8.5,8.4,12.1,2.6,2021-08-01
2,Alzey-Worms,5130.0,1.0,304.0,123.0,4970.0,37.0,9.3,24.0,4.4,8.2,2021-08-01
3,Bad Dürkheim,4499.0,1.0,305.0,150.0,4303.0,46.0,14.3,21.6,19.5,2.3,2021-08-01
4,Bad Kreuznach,6121.0,0.0,160.0,142.0,5923.0,56.0,18.3,41.4,20.0,2.0,2021-08-01

In [148]:
df2 = df2[df2['District'].notna()]

object_cols = list(df2.select_dtypes(include='object'))
for cols in object_cols:
    df2 = df2[df2[col].notna()]

In [149]:
object_cols

['District', 'Date']

In [150]:
calculate_null_percentage(df2)

Columns with null percentage:
0
District                                                                        0.0
Laboratory confirmed, since the beginning of the pandemic TOTAL                 0.0
Laboratory confirmed, since the beginning of the pandemic Difference from       0.0
Laboratory confirmed, since the beginning of the pandemic Hospitalized          0.0
Laboratory confirmed, since the beginning of the pandemic Deceased              0.0
Laboratory confirmed, since the beginning of the pandemic RecoveredA            0.0
Laboratory confirmed, since the beginning of the pandemic Current CasesB        0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD          0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre       0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE    0.0
Reported, the last 7 days,Incidence per 100, Incidence per 100 ,>=60 Jahre      0.0
Date                                                                            0.0
dtype: float64

In [151]:
df2.isnull().values.any()

False

In [152]:
len(df2)

16700

In [153]:
df2.head()

,District,"Laboratory confirmed, since the beginning of the pandemic TOTAL","Laboratory confirmed, since the beginning of the pandemic Difference from","Laboratory confirmed, since the beginning of the pandemic Hospitalized","Laboratory confirmed, since the beginning of the pandemic Deceased","Laboratory confirmed, since the beginning of the pandemic RecoveredA","Laboratory confirmed, since the beginning of the pandemic Current CasesB","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,+USAFD","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,<20 Jahre","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,20-59 JahreE","Reported, the last 7 days,Incidence per 100, Incidence per 100 ,>=60 Jahre",Date
0,Ahrweiler,4577.0,4.0,199.0,52.0,4423.0,102.0,50.0,132.2,49.0,7.1,2021-08-01
1,Altenkirchen,4956.0,0.0,411.0,101.0,4833.0,22.0,8.5,8.4,12.1,2.6,2021-08-01
2,Alzey-Worms,5130.0,1.0,304.0,123.0,4970.0,37.0,9.3,24.0,4.4,8.2,2021-08-01
3,Bad Dürkheim,4499.0,1.0,305.0,150.0,4303.0,46.0,14.3,21.6,19.5,2.3,2021-08-01
4,Bad Kreuznach,6121.0,0.0,160.0,142.0,5923.0,56.0,18.3,41.4,20.0,2.0,2021-08-01

In [154]:
df2.to_excel('final_cleaned_TimeSeries_dataset.xlsx' )

In [155]:
del df2["Date"]
df2.to_excel('final_cleaned_dataset.xlsx' )